Make cache for npm and pip

diff --git a/bin/ready b/bin/ready
--- a/bin/ready
+++ b/bin/ready
@@ -1,21 +1,38 @@
 #!/bin/bash -u
 
-declare -r READY_LIB_DIR=${READY_LIB_DIR:-"$(dirname $BASH_SOURCE)/../lib/ready"}
-
-declare RC_FILE="${PWD}/.readyrc"
-if [[ "$#" = "1" ]]; then
-    RC_FILE="${PWD}/$1"
-fi
-declare -r RC_FILE
+declare READY_RESULT=0
+declare -r READY_TEMP_DIR=$(mktemp --tmpdir -d ready.XXXXXXXXXX)
 
 # Import functions
-source "$READY_LIB_DIR/ready_lib.sh"
 
-if [[ ! -f "$RC_FILE" ]]; then
-    log_error "File not found: $RC_FILE"
+declare -r READY_LIB_DIR=${READY_LIB_DIR:-"$(dirname $BASH_SOURCE)/../lib/ready"}
+
+source "$READY_LIB_DIR/logger.sh"
+source "$READY_LIB_DIR/output.sh"
+
+source "$READY_LIB_DIR/check_command.sh"
+
+source "$READY_LIB_DIR/check_node.sh"
+source "$READY_LIB_DIR/check_python.sh"
+
+# Execute READYRC_FILE
+
+declare READYRC_FILE="${PWD}/.readyrc"
+if [[ "$#" = "1" ]]; then
+    READYRC_FILE="${PWD}/$1"
+fi
+declare -r READYRC_FILE
+
+if [[ ! -f "$READYRC_FILE" ]]; then
+    log_error "File not found: $READYRC_FILE"
     exit 1
 fi
 
-# Execute RC_FILE
-log_debug "Execute: $RC_FILE"
-source "$RC_FILE"
+log_debug "Execute: $READYRC_FILE"
+source "$READYRC_FILE"
+
+# Cleanup
+
+rm -rf "$READY_TEMP_DIR"
+
+exit $READY_RESULT
